### ISSUE TITLE
よしななタグを追加

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#1]
@materialofmouse @Atria64 @t4t5u0 
HARAHERIとかNARUHAYAとかいい感じにタグを追加しようぜ

**Comment by Atria64** [comment]
考えた感じ
   
 - Front
 - Back
 - UI
 - Test
 - Refactoring
 - High-priority
 - Low-priority
   
とかだろうか

**Comment by materialofmouse** [comment]
- Yoshinani
- Haraheri

**Comment by yuhi-dosei** [comment]
追加したのでクローズ
