### ISSUE TITLE
DBのテーブル自動作成

### ISSUE THREAD

**Issue by materialofmouse** [FunLocks/team2001#102]
dockerのentrypointの起動をつかって、テーブル定義を自動で行う。
@t4t5u0 SQL文ファイルにしてback/mysql配下に作成して下さい。

**Comment by t4t5u0** [comment]
goの中で直接作ってたから、空のデータベースしか作ってないんだよね。それでも必要ならやっとく

**Comment by materialofmouse** [comment]
そしたら、go動かすと勝手にテーブル定義されるの？

**Comment by t4t5u0** [comment]
うん。あ、でも今は最初にデータが飛んできたにやってた気がするから起動時にチェックするように変えとくね

**Comment by materialofmouse** [comment]
あー、把握、それだと助かる。

**Comment by t4t5u0** [comment]
あーでも、多分 create database hoge は叩けない。どうする？

**Comment by materialofmouse** [comment]
create databaseはいらない。test1のtableは自分で定義したの？

**Comment by materialofmouse** [comment]
docker-composeでdatabase自動作成。
goの方でtable作成するので問題ない
