### ISSUE TITLE
アプリの紹介画像

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#110]
## 欲しい機能はどのようなものか
ahchooのロゴとアプリのメイン画面をはめ込んだ画像

## 参考URL/資料
https://i.ytimg.com/vi/aHjhJfW-6MI/maxresdefault.jpg

**Comment by HiromuYoshida** [comment]
左側のスマホの画面をマップの画像に変えたら終了です
![promotion_アートボード 1](https://user-images.githubusercontent.com/58163848/102621101-733f1500-4182-11eb-9dea-28d7064bdd8a.png)

**Comment by HiromuYoshida** [comment]
![promotion_ver_com_アートボード 1](https://user-images.githubusercontent.com/58163848/102664749-c9ce4280-41c6-11eb-86f2-32098a681558.png)

作り終えたので閉じる
