### ISSUE TITLE
Enterprize版のロゴ画像

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#111]
## 欲しい機能はどのようなものか
メインロゴにEnterprizeの文字を追加

## 参考URL/資料
![spotify_premium](https://user-images.githubusercontent.com/37332703/102488055-d1022d00-40ae-11eb-9af1-8c82167232c2.png)

**Comment by HiromuYoshida** [comment]
![スクリーンショット 2020-12-18 8 45 40](https://user-images.githubusercontent.com/58163848/102562315-2a537600-411a-11eb-9975-35938309734b.png)
これらのパターンから選定
その後調節後に完成予定

**Comment by HiromuYoshida** [comment]
上から3番目のロゴに決定
よってこのissue閉じます
