### ISSUE TITLE
APIKEYをPUSHしない！！！！！！！

### ISSUE THREAD

**Issue by t4t5u0** [FunLocks/team2001#117]
## どのような不具合を確認しましたか?

Google APIKEY が PUSH されています．早急に更新し，ignoreしてください

## 発生したときの環境
 - PC/Tablet/Mobile
 - OS名とバージョン
 - 利用ブラウザ名とバージョン

**Comment by t4t5u0** [comment]
とりあえず消した

**Comment by materialofmouse** [comment]
APIキー削除
