### ISSUE TITLE
POST時にサーバー側でエラーが出る。

### ISSUE THREAD

**Issue by materialofmouse** [FunLocks/team2001#121]
parse "https://maps.googleapis.com/maps/api/geocode/json?latlng=41.84201720061932,140.76738712083056&location_type=ROOFTOP&result_type=street_address&key={API key}  \n": net/url: invalid control character in URL
ってなってる。
ファイル読み込みの時点で改行コードまで読んでいる気がする。

**Comment by t4t5u0** [comment]
naruhodo

**Comment by t4t5u0** [comment]
修正してみる．暫定回答は改行消すこと
