### ISSUE TITLE
CORSエラー

### ISSUE THREAD

**Issue by Atria64** [FunLocks/team2001#139]
## どのような不具合を確認しましたか?
CORSエラーと出てfetchできない

### 不具合発生時のスクリーンショット
![image](https://user-images.githubusercontent.com/49768768/102642162-9a0c4400-41a0-11eb-9c67-9ce85124f43c.png)

## 不具合の発生手順
react で http://153.120.166.49:8080/get にアクセス

## 本来どのような動作が望ましいか
APIのフェッチ

**Comment by materialofmouse** [comment]
あとりあで確認できました。

**Comment by materialofmouse** [comment]
https://github.com/gin-contrib/cors

**Comment by materialofmouse** [comment]
本番サーバーでの動作確認した　。
