### ISSUE TITLE
Androidの機能洗い出し

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#14]
ボタンを押して音が流れる

マップで咳の状態が見れる

**Comment by Atria64** [comment]
# 起動時
 - アプリアイコンを真ん中に出す

# ウォークスルー
 - 画像&テキストの表示
 - スワイプ

# メインアクティビティ
 - ボタン
   - 押下で音が流れる
   - 押下で位置情報の記録をサーバに飛ばす
   - 押下でライトをチカチカさせる
     - ダサさからPro版への誘導につなげる
 - Webへの誘導ボタン or ナビゲーション?

**Comment by Atria64** [comment]
あらかた洗い出した。   
残りは開発しながらやります。
