### ISSUE TITLE
アピールシートの内容を埋める

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#145]
スクリーンショット(任意)
開発体制

役割分担
...

オンライン開発における工夫した点
...

開発技術(任意)
利用したプログラミング言語
...

利用したフレームワーク・ライブラリ
...

その他開発に使用したツール

**Comment by t4t5u0** [comment]
スクリーンショット(任意)
開発体制

役割分担
バックエンド，サーバ

オンライン開発における工夫した点
GitHub, Slack, Discord などを活用した適切なコミュニケーション

開発技術(任意)
利用したプログラミング言語
- Go
- 

利用したフレームワーク・ライブラリ
- gin
- gorm
- docker
- git
- 

その他開発に使用したツール
- GitHub

**Comment by materialofmouse** [comment]
スクリーンショット(任意)
開発体制
 - バック:2人で分担。
役割分担
 - ハードウェアの作成
 - ハード制御用ソフトウェアの作成
 - dockerを用いた開発環境構築の自動化
 - バック

オンライン開発における工夫した点
 - どうしても対面で合うときとオンラインでできる時を分けた。
 - dockerを用いて本番サーバーの環境を自動で構築できるようにしたので、開発者がローカルでサーバーを立てて開発をすすめられるようにした。
 
開発技術(任意)
利用したプログラミング言語
- python
- go

利用したフレームワーク・ライブラリ
- MicropyGPS
- docker
- docker-compose

その他開発に使用したツール
 - Github
 - カッター
 - SSR
 - raspberry pi zero WH

**Comment by Atria64** [comment]
スクリーンショット(任意)
開発体制
 - Android
   - 畑一人で担当
 - Web(React)
   - 畑一人で担当
 - Design
   - 吉田一人で担当
  
役割分担
...
同上
オンライン開発における工夫した点
...
 - 会議にはカメラを利用することで交換する情報量が多くなるように努めた。
 - デザインの共有には専用ツールである `xd.adobe.com` を利用した。
開発技術(任意)
利用したプログラミング言語
...
### Android
 - Kotlin
### Web
 - JSX

利用したフレームワーク・ライブラリ
...
### Android
 - androidx
 - Preference
 - okhttp3
 - Camera2 API
### Web
 - React
 - google-map-react

その他開発に使用したツール
 - Windows 10
 - GitHub
 - Git
 - Node.js
 - Illustrator
 - Adobe XD
 - Photoshop
 - Adobe Premia Pro
