### ISSUE TITLE
期間ごとにあちょーをとってほしい(ahchooget)

### ISSUE THREAD

**Issue by Atria64** [FunLocks/team2001#148]
## 欲しい機能はどのようなものか
 - 1時間以内のAHCHOO!
 - 1日以内のAHCHOO!
 - 1週間以内のAHCHOO!
    
をgetしたい

## image(左のところに入れたい)
![image](https://user-images.githubusercontent.com/49768768/102659400-ab634980-41bc-11eb-894f-cc54c4c84a71.png)

**Comment by t4t5u0** [comment]
done
