### ISSUE TITLE
ハードウェアに必要な部品洗い出し

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#15]
ボタン
赤色灯
スピーカー
バッテリーの有無

**Comment by materialofmouse** [comment]
ボタン：良さげなの。高くてもいいから大きくて押し心地のいいもの。
赤色灯：電圧と電流によっては外部電源の用意をしなければいけない。できるなら5V0.5A程度のものを選びたい。
スピーカー：ちょくスピーカーか、ジャック変換かを選ぶ。
バッテリー：積むならモバイルバッテリーとかになるかな。給電usb-microBだし。

**Comment by materialofmouse** [comment]
## スピーカー
スピーカーは内蔵しない。
ジャックに変換して外部スピーカー使います。（内蔵スピーカーだと出力が小さい）
持ち運びとかはしにくくなるけど我慢してください。

**Comment by materialofmouse** [comment]
## バッテリー
バッテリーはどっちでもいい。
自分コンセントtoUSBもあるし、モバイルバッテリーもあるから今回は購入しない。

**Comment by materialofmouse** [comment]
# 購入するもの
## ボタン
https://www.monotaro.com/g/00022650/?monotaroNo=6927164
ABS310NBを１つお願いします。

## パトランプ
https://www.monotaro.com/g/00511451/?monotaroNo=50320821
ORL-3を１つお願いします。
@yuhi-dosei
