### ISSUE TITLE
Front:ボタンを押すと音が流れる

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#16]

**Comment by Atria64** [comment]
画像に対してボタンの処理を加える形になりそう

**Comment by Atria64** [comment]
# 使用する技術
今回は5秒以上の音声を再生するため、MediaPlayerを採用する。   
[MediaPlayer  |  Android デベロッパー  |  Android Developers ](https://developer.android.com/reference/android/media/MediaPlayer )
[[Android] SoundPool で効果音を鳴らしてみる](https://akira-watson.com/android/soundpool.html )

**Comment by Atria64** [comment]
[[Android] 簡単なMediaPlayerで音楽を再生する](https://akira-watson.com/android/audio-player.html)
> MediaPlayerの特徴としては、呼び出してから再生まである程度時間がかかります。ゲームで言うとBGMを流しっぱなしには向きますが、爆発音を出したい時はタイミングが合わないかもしれません。
   
ちょっと怖い

**Comment by Atria64** [comment]
0.5秒くらいの遅れがある   
ユーザがギリ知覚できる程度
