### ISSUE TITLE
Frontラベルの削除

### ISSUE THREAD

**Issue by Atria64** [FunLocks/team2001#25]
WebラベルとAndroidラベルを作成したため、Frontラベルは必要がないように思えます。   
Frontに関わる @yuhi-dosei か @HiromuYoshida のどちらかの意見が欲しいです。

**Comment by yuhi-dosei** [comment]
同意
Frontは仮だったので分けよう

**Comment by Atria64** [comment]
Frontラベルを削除しました。助かりっ！
