### ISSUE TITLE
トイレ行った

### ISSUE THREAD

**Issue by yuhi-dosei** [FunLocks/team2001#30]
## どのような不具合を確認しましたか?
トイレが寒い

## 不具合の発生手順
暖房をつけてなかった

## 本来どのような動作が望ましいか
トイレが暖かい

## 発生したときの環境
 - PC/Tablet/Mobile
 - OS名とバージョン
 - 利用ブラウザ名とバージョン

**Comment by materialofmouse** [comment]
確認しました。
