### ISSUE TITLE
データ形式とトリガー

### ISSUE THREAD

**Issue by materialofmouse** [FunLocks/team2001#55]
JSONを用いてデータのやり取りを行う。

## サーバー情報
 - IP:153.120.166.49
 - port:8000

### PRO(POST) 
- データ:GPSの緯度経度
- トリガー:ボタンを押したとき。

### PRO(GET)
- なし

### Android(POST)
- データ:GPSの緯度経度
- トリガー:ボタンを押したとき。

### Android(GET)
- 現状なし

### MAP(GET)
- データ:GPSの緯度経度(サーバー側でデータ補完したあとの緯度経度)
- トリガー:Always
わんちゃんwebsocketとか使って通信してもいいかも？

**Comment by Atria64** [comment]
@yuhi-dosei これら確定したらWikiに書いてまとめてくれると嬉しい
