### ISSUE TITLE
はらへりあ

### ISSUE THREAD

**Issue by Atria64** [FunLocks/team2001#62]
セブン行ってなにか買います。   
おすすめを教えて下さい。

**Comment by yuhi-dosei** [comment]
カリカリコーン
コンソメ味 100えん
味が濃いのと手に匂いがつくので箸で食べよう

**Comment by marbou090** [comment]
いちごオレ
１００えんくらい
おいしかった

**Comment by t4t5u0** [comment]
おにぎり(鮭) メロンパン 麦茶 で爆速退店

**Comment by Oxypetalum7** [comment]
サワークリーム味のポテチ
僕は好きです。

**Comment by Atria64** [comment]
@Oxypetalum7 ごめんなさいあんまり得意じゃないので別のアイディアほしいです

**Comment by kota-shiokara** [comment]
セブンプレミアム　そのまま食べるぶどう

**Comment by ryusuke920** [comment]
唐揚げ棒×５で唐揚げ弁当

**Comment by Yuto5176** [comment]
夜食には少し高いがラーメンサラダ
食べた後気持ち悪くならない

**Comment by yatoto** [comment]
おでん，肉まんが最強

**Comment by Oxypetalum7** [comment]
三角のパッケージの鳥皮

**Comment by Sorasky4** [comment]
まるごとバナナ
糖分補給したいよね

**Comment by Atria64** [comment]
締め切ります

**Comment by Atria64** [comment]
![image](https://user-images.githubusercontent.com/49768768/102240789-96c44e80-3f3b-11eb-9e23-501743074a79.png)
# Special Thanks
@yuhi-dosei 買えた
@marbou090 売ってなかったので別のいちごで対応
@t4t5u0 全部買えた
@Oxypetalum7 売ってなかった
@kota-shiokara 買えた
@ryusuke920 売ってなかった
@Yuto5176 買えた
@yatoto どっちも売ってなかった
@Sorasky4 バナナなかった

**Comment by Atria64** [comment]
おいしかった。   
おなかいっぱい。
