### ISSUE TITLE
JSONに時間を含めるかどうか

### ISSUE THREAD

**Issue by t4t5u0** [FunLocks/team2001#82]
POSTするJSONに時間を含めるかどうか．サーバ側で，到着した時間を挿入するほうが楽な気がしてきた

**Comment by materialofmouse** [comment]
POSTのときにサーバー側で到達時間処理でいいと思います。
とりあえず増やすのめんどくさいので、DB側に
 - 時間
 - latitude
 - longitude
 - 温度
 - 気圧

を保存する感じでお願いしていいですか？
温度と気圧はAHCHOO Enterpriseで使います。

**Comment by t4t5u0** [comment]
データ増やすのね．わかった
