### ISSUE TITLE
円が広がるアニメーションの作成

### ISSUE THREAD

**Issue by HiromuYoshida** [FunLocks/team2001#89]
## 欲しい機能はどのようなものか
くしゃみした時の場所から円が広がるようなアニメーションを制作

## なぜその機能がほしいのか
必須。これがないと話にならない。

## 実装方法
CSSアニメーションorP5.js

## 参考URL/資料
https://qiita.com/koedamon/items/2665ea80f19589aa2f7d

**Comment by Atria64** [comment]
円が広がるアニメーション
https://codepen.io/atria64/pen/YzGVapj
   
書いてみました
