### ISSUE TITLE
データ挿入されなくて悲しい

### ISSUE THREAD

**Issue by t4t5u0** [FunLocks/team2001#93]
### 不具合発生時のスクリーンショット
![image](https://user-images.githubusercontent.com/48282855/102372394-80cd9100-4002-11eb-808d-d123ca39043e.png)

## 発生したときの環境
 - PC/Tablet/Mobile
 - OS名とバージョン
 - 利用ブラウザ名とバージョン

**Comment by t4t5u0** [comment]
![image](https://user-images.githubusercontent.com/48282855/102374606-e02ca080-4004-11eb-9c29-bf8b750a0c1e.png)
型情報．なんでNULLになる

**Comment by materialofmouse** [comment]
どんなsql文で挿入したか知りたい

**Comment by materialofmouse** [comment]
挿入したデータの範囲がおかしいとなりそう

**Comment by t4t5u0** [comment]
動いた！！！！！！

挿入するデータがおかしかったっぽ

**Comment by t4t5u0** [comment]
![Uploading image.png…]()

**Comment by materialofmouse** [comment]
サポートしている範囲は '1000-01-01 00:00:00.000000' から '9999-12-31 23:59:59.999999' です。
ってあるからこの範囲外だったのかもね
